server:
  port: 80
  tomcat:
    #更改tomcat缓存目录
    basedir: D:/Tomcat/home/tomcat
spring:
  application:
    #项目应用名称,默认时自己的工程名称
    name: lucky-app
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///reggie
    username: root
    password: llh105406
  #web:
    #resources:
      #静态资源路径设置
      #static-locations: [classpath:backend/]
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.reggie.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
  #通用枚举包
  type-enums-package: com.example.reggie.enums
#自定义参数
reggie:
  path: D:/javaProject/SpringBoot项目/lucky-app/src/main/resources/backend/images/menus/

